[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

[entryPoints.http.redirect]
regex = "^http:\/\/(example\.com)(.*)"
replacement = "http://www.$1/$2"
permanent = true